environments:
  dev:
    base_url: https://web.dev.cofee.life
    timeout: 30000
  stg:
    base_url: https://web.stg.cofee.life
    timeout: 30000

browsers:
  - chromium

viewports:
  desktop:
    width: 1440
    height: 900
